### ISSUE TITLE
Please include "systemd-run" in initrd

### ISSUE THREAD

**Issue by mvo5** [snapcore/core-initrd#10]
The UC20 full-disk-encryption will provide a way to run helpers to support special hardware for the encryption. To support this we need to run a new "fde-reveal-key" binary as part of initramfs. We would like to run this binary with systemd-run to benefit from some of the systemd features like automatic kill after a certain timeout and doing some basic sandboxing around it. This is sketched in https://github.com/snapcore/snapd/pull/9488

For this to work we would like to ask to include systemd-run inside the initramfs. If it's too much of an issue or too big we could as only the custom kernels to include it or we could drive systemd via the dbus API but for simplicity we would like to have the binary as our first choice.

**Comment by xnox** [comment]
between dbus and systemd-run, you will get systemd-run binary =)

**Comment by anonymouse64** [comment]
Don't mean to throw fire on using systemd-run, I'm certainly a fan of having binaries like this which DTRT, but in snapd we already have code for generating systemd units, is it very difficult to adapt that code to also be able to generate these services dynamically too?

**Comment by anonymouse64** [comment]
Sure, I don't know how much customization we need to make for these units, but afaict, to do so without systemd-run would just be generating a .service file and dropping it in `/run/systemd/system/...` and then doing `systemctl enable` or `systemctl start` on it. If these units are fairly simple then I don't think it would be a lot of code, but then again it is certainly probably more code than `exec.Command("systemd-run","--some-options",...).CombinedOutput()`.
