### ISSUE TITLE
Start running spread tests

### ISSUE THREAD

**Issue by xnox** [snapcore/core-initrd#4]
spread tests were merged.

Please add keys/actions/stuff to this repo to start running tests.

@niemeyer @anonymouse64

**Comment by anonymouse64** [comment]
@xnox I have a PR up with the travis.yml to run in travis, we just need to setup GCE keys with @niemeyer, but you also need to enable travis on this PR, as it seems that the travis check isn't running on #5

**Comment by xnox** [comment]
Travis is setup, and failing with "spread couldn't allocate gce......" because token/secret is not there.
