### ISSUE TITLE
Use snap-bootstrap from master snapd branch when possible

### ISSUE THREAD

**Issue by alfonsosanchezbeato** [snapcore/core-initrd#44]
Currently we build `snap-bootstrap` from https://github.com/xnox/snapd/tree/run-cloudimg-rootfs-draft-1 instead of using https://github.com/snapcore/snapd so cloud images are supported. Use master as soon as that branch is merged.

**Comment by xnox** [comment]
> Currently we build `snap-bootstrap` from https://github.com/xnox/snapd/tree/run-cloudimg-rootfs-draft-1 instead of using https://github.com/snapcore/snapd so cloud images are supported. Use master as soon as that branch is merged.

that's not quite true.

core-initrd has two snap-bootstraps. The one for ubuntu-core mode (main) is used as whatever snapd team uploads into snappy-dev/image ppa in production builds.

the one used for cloudimg-rootfs mode only is a temporary fork.

**Comment by xnox** [comment]
this fork got merged, and we ship only one snapd-bootstrap now.
